import { SquareContents } from '../../types';
import { setUpSquare, EmptySquare } from '../basic/pieces';

const emptyBoard: SquareContents[][] = [
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
  // [
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  //   setUpSquare(EmptySquare(), 2, 2, false),
  // ],
];

export default emptyBoard;
