import { SquareContents } from '../../types';
import { setUpSquare, EmptySquare } from '../piecesBasic';

const emptyBoard: SquareContents[][] = [
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
  [
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
    setUpSquare(EmptySquare(), 2, 2, false),
  ],
];

export default emptyBoard;
